#!/bin/bash
# shellcheck disable=SC1091
source common.sh
resources=("modelregistries.modelregistry.opendatahub.io")
# Dependent resources ossm
resources+=("authorizationpolicies" "destinationrules" "gateways" "virtualservices")

nslist=$(get_all_namespace "${resources[@]}")

run_mustgather "${nslist[@]}"
